import 'dart:math';
import '../../models/item.dart';
import '../../models/item_rarity.dart';
import '../../models/buff_type.dart';
import '../../models/buff_duration.dart';

/// Template de item para geração randômica
class ItemTemplate {
  final String nome;
  final String descricao;
  final ItemType tipo;
  final ItemRarity raridade;
  final int precoBase;
  final int espacoUnitario;
  final int patenteMinima;
  final int nexMinimo; // NEX mínimo para usar o item

  // Campos específicos
  final String? formulaDano;
  final int? multiplicadorCritico;
  final String? efeitoCritico;
  final bool isAmaldicoado;
  final String? efeitoMaldicao;
  final String? formulaCura;
  final String? efeitoAdicional;
  final int? defesaBonus;

  // Buffs
  final BuffType? buffTipo;
  final String? buffDescricao;
  final BuffDuration? buffDuracao;
  final int? buffTurnos;
  final int? buffValor;

  const ItemTemplate({
    required this.nome,
    required this.descricao,
    required this.tipo,
    this.raridade = ItemRarity.comum,
    required this.precoBase,
    this.espacoUnitario = 1,
    this.patenteMinima = 0,
    this.nexMinimo = 5, // NEX padrão 5% (iniciante)
    this.formulaDano,
    this.multiplicadorCritico,
    this.efeitoCritico,
    this.isAmaldicoado = false,
    this.efeitoMaldicao,
    this.formulaCura,
    this.efeitoAdicional,
    this.defesaBonus,
    this.buffTipo,
    this.buffDescricao,
    this.buffDuracao,
    this.buffTurnos,
    this.buffValor,
  });
}

/// Banco de dados de templates de itens
class ItemTemplateDatabase {
  // ========== ARMAS COMUNS ==========

  static const List<ItemTemplate> armasComuns = [
    // Pistolas
    ItemTemplate(
      nome: 'Glock 17',
      descricao: 'Pistola semi-automática 9mm confiável e popular entre agentes.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 1200,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaDano: '1d6',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Beretta 92',
      descricao: 'Pistola italiana robusta, usada por forças militares.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 1400,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaDano: '1d6+1',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Desert Eagle',
      descricao: 'Pistola de alto calibre com grande poder de parada.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 2500,
      espacoUnitario: 2,
      patenteMinima: 1,
      formulaDano: '1d10',
      multiplicadorCritico: 2,
      efeitoCritico: 'Recuo forte, -1 próximo ataque',
    ),

    // Revólveres
    ItemTemplate(
      nome: 'Colt Python',
      descricao: 'Revólver .357 Magnum clássico, preciso e confiável.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 1800,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaDano: '1d8',
      multiplicadorCritico: 3,
    ),
    ItemTemplate(
      nome: 'Smith & Wesson 500',
      descricao: 'Revólver de altíssimo calibre, devastador mas difícil de controlar.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 3500,
      espacoUnitario: 2,
      patenteMinima: 2,
      nexMinimo: 20,
      formulaDano: '2d6',
      multiplicadorCritico: 3,
      efeitoCritico: 'Recuo extremo, -2 próximo ataque',
    ),

    // Rifles
    ItemTemplate(
      nome: 'AR-15',
      descricao: 'Rifle semi-automático versátil, padrão para operações táticas.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 3000,
      espacoUnitario: 3,
      patenteMinima: 1,
      formulaDano: '1d8+2',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'AK-47',
      descricao: 'Rifle de assalto robusto, funciona em qualquer condição.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 2800,
      espacoUnitario: 3,
      patenteMinima: 1,
      formulaDano: '1d10',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Barrett M82',
      descricao: 'Rifle anti-material .50 BMG, capaz de perfurar veículos.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 8000,
      espacoUnitario: 5,
      patenteMinima: 3,
      nexMinimo: 35,
      formulaDano: '2d10+2',
      multiplicadorCritico: 3,
      efeitoCritico: 'Penetra cobertura leve',
    ),

    // Espingardas
    ItemTemplate(
      nome: 'Remington 870',
      descricao: 'Espingarda pump-action 12 calibre, devastadora a curta distância.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 1500,
      espacoUnitario: 3,
      patenteMinima: 0,
      formulaDano: '2d6',
      multiplicadorCritico: 2,
      efeitoCritico: 'Alvos próximos recuam 1 metro',
    ),
    ItemTemplate(
      nome: 'SPAS-12',
      descricao: 'Espingarda tática italiana, modo pump ou semi-automático.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 2200,
      espacoUnitario: 3,
      patenteMinima: 1,
      formulaDano: '2d6+1',
      multiplicadorCritico: 2,
    ),

    // Submetralhadoras
    ItemTemplate(
      nome: 'MP5',
      descricao: 'Submetralhadora compacta alemã, ideal para espaços fechados.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 2500,
      espacoUnitario: 2,
      patenteMinima: 1,
      formulaDano: '1d6',
      multiplicadorCritico: 2,
      efeitoCritico: 'Rajada: +1d6 dano',
    ),
    ItemTemplate(
      nome: 'Uzi',
      descricao: 'Submetralhadora israelense compacta, alta cadência de tiro.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 2000,
      espacoUnitario: 2,
      patenteMinima: 1,
      formulaDano: '1d6',
      multiplicadorCritico: 2,
    ),

    // Armas brancas
    ItemTemplate(
      nome: 'Faca de Combate',
      descricao: 'Faca tática de lâmina fixa, silenciosa e letal.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 300,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaDano: '1d4+1',
      multiplicadorCritico: 3,
    ),
    ItemTemplate(
      nome: 'Machete',
      descricao: 'Facão pesado, eficaz contra múltiplos alvos.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 200,
      espacoUnitario: 2,
      patenteMinima: 0,
      formulaDano: '1d6+2',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Katana',
      descricao: 'Espada japonesa afiada, requer treinamento mas é devastadora.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 2000,
      espacoUnitario: 2,
      patenteMinima: 2,
      nexMinimo: 20,
      formulaDano: '1d10+1',
      multiplicadorCritico: 3,
      efeitoCritico: 'Corte preciso: +1d6 sangramento',
    ),
    ItemTemplate(
      nome: 'Taco de Basebol',
      descricao: 'Improvisado mas eficaz, intimida inimigos.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 100,
      espacoUnitario: 2,
      patenteMinima: 0,
      formulaDano: '1d6',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Barra de Ferro',
      descricao: 'Pesada e brutal, causa dano contundente severo.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 80,
      espacoUnitario: 2,
      patenteMinima: 0,
      formulaDano: '1d8',
      multiplicadorCritico: 2,
      efeitoCritico: 'Atordoa por 1 turno',
    ),

    // Arcos e bestas
    ItemTemplate(
      nome: 'Arco Composto',
      descricao: 'Arco moderno silencioso, ideal para operações furtivas.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 1500,
      espacoUnitario: 2,
      patenteMinima: 1,
      formulaDano: '1d8',
      multiplicadorCritico: 3,
    ),
    ItemTemplate(
      nome: 'Besta Tática',
      descricao: 'Besta moderna com mira telescópica, silenciosa e letal.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 1800,
      espacoUnitario: 3,
      patenteMinima: 1,
      formulaDano: '1d10',
      multiplicadorCritico: 3,
      efeitoCritico: 'Perfura armadura leve',
    ),

    // Armas exóticas
    ItemTemplate(
      nome: 'Lança-chamas Portátil',
      descricao: 'Arma experimental que projeta fogo, aterrorizante.',
      tipo: ItemType.arma,
      raridade: ItemRarity.lendario,
      precoBase: 15000,
      espacoUnitario: 4,
      patenteMinima: 4,
      nexMinimo: 50,
      formulaDano: '2d8',
      multiplicadorCritico: 2,
      efeitoCritico: 'Área 3m cone, ignição',
    ),

    // MAIS PISTOLAS
    ItemTemplate(
      nome: 'Sig Sauer P226',
      descricao: 'Pistola suíça de precisão, usada por forças especiais.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 1600,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaDano: '1d6+1',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'FN Five-Seven',
      descricao: 'Pistola belga que dispara munição perfurante 5.7mm.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 2200,
      espacoUnitario: 1,
      patenteMinima: 2,
      formulaDano: '1d8',
      multiplicadorCritico: 2,
      efeitoCritico: 'Perfura armadura leve',
    ),
    ItemTemplate(
      nome: 'CZ 75',
      descricao: 'Pistola tcheca robusta e precisa.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 1300,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaDano: '1d6',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Walther PPK',
      descricao: 'Pistola compacta discreta, favorita de espiões.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 1100,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaDano: '1d4+2',
      multiplicadorCritico: 3,
    ),
    ItemTemplate(
      nome: 'Taurus Judge',
      descricao: 'Revólver que dispara tanto .45 quanto calibre 12.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 1900,
      espacoUnitario: 2,
      patenteMinima: 1,
      formulaDano: '1d10',
      multiplicadorCritico: 2,
    ),

    // MAIS RIFLES
    ItemTemplate(
      nome: 'M16A4',
      descricao: 'Rifle militar americano padrão com modo burst.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 3200,
      espacoUnitario: 3,
      patenteMinima: 1,
      formulaDano: '1d8+2',
      multiplicadorCritico: 2,
      efeitoCritico: 'Burst: dispara 3 vezes',
    ),
    ItemTemplate(
      nome: 'FN SCAR',
      descricao: 'Rifle modular de combate, extremamente versátil.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 4500,
      espacoUnitario: 3,
      patenteMinima: 2,
      formulaDano: '1d10+1',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'HK G36',
      descricao: 'Rifle de assalto alemão leve e preciso.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 3400,
      espacoUnitario: 3,
      patenteMinima: 1,
      formulaDano: '1d8+2',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Winchester Modelo 70',
      descricao: 'Rifle de caça clássico, extremamente preciso.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 2400,
      espacoUnitario: 3,
      patenteMinima: 1,
      formulaDano: '1d10+2',
      multiplicadorCritico: 3,
    ),
    ItemTemplate(
      nome: 'Dragunov SVD',
      descricao: 'Rifle de precisão russo semi-automático.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 5500,
      espacoUnitario: 4,
      patenteMinima: 2,
      formulaDano: '2d6+2',
      multiplicadorCritico: 3,
    ),
    ItemTemplate(
      nome: 'Remington 700',
      descricao: 'Rifle de precisão bolt-action, favorito de atiradores de elite.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 3800,
      espacoUnitario: 4,
      patenteMinima: 2,
      formulaDano: '2d6',
      multiplicadorCritico: 3,
    ),
    ItemTemplate(
      nome: 'Tavor TAR-21',
      descricao: 'Rifle bullpup israelense compacto e moderno.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 4200,
      espacoUnitario: 2,
      patenteMinima: 2,
      formulaDano: '1d8+3',
      multiplicadorCritico: 2,
    ),

    // MAIS ESPINGARDAS
    ItemTemplate(
      nome: 'Benelli M4',
      descricao: 'Espingarda semi-automática italiana tática.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 2600,
      espacoUnitario: 3,
      patenteMinima: 1,
      formulaDano: '2d6+1',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Mossberg 500',
      descricao: 'Espingarda pump confiável, usada por policiais.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 1400,
      espacoUnitario: 3,
      patenteMinima: 0,
      formulaDano: '2d6',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Winchester 1897',
      descricao: 'Espingarda pump clássica da Primeira Guerra.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 1200,
      espacoUnitario: 3,
      patenteMinima: 0,
      formulaDano: '2d6-1',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'AA-12',
      descricao: 'Espingarda automática devastadora, alto recuo.',
      tipo: ItemType.arma,
      raridade: ItemRarity.lendario,
      precoBase: 12000,
      espacoUnitario: 4,
      patenteMinima: 4,
      formulaDano: '2d8+2',
      multiplicadorCritico: 2,
      efeitoCritico: 'Modo automático: dispara 3 vezes',
    ),

    // MAIS SUBMETRALHADORAS
    ItemTemplate(
      nome: 'P90',
      descricao: 'SMG belga futurística com carregador de 50 balas.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 3200,
      espacoUnitario: 2,
      patenteMinima: 2,
      formulaDano: '1d6+1',
      multiplicadorCritico: 2,
      efeitoCritico: 'Rajada extensa: +2d6',
    ),
    ItemTemplate(
      nome: 'Thompson M1928',
      descricao: 'Metralhadora clássica da era da Lei Seca.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 2800,
      espacoUnitario: 3,
      patenteMinima: 1,
      formulaDano: '1d8',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Scorpion vz. 61',
      descricao: 'Micro SMG tcheca extremamente compacta.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 1800,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaDano: '1d4+1',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Kriss Vector',
      descricao: 'SMG moderna com sistema anti-recuo revolucionário.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 3600,
      espacoUnitario: 2,
      patenteMinima: 2,
      formulaDano: '1d8+1',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'MAC-10',
      descricao: 'SMG barata com alta cadência de tiro.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 1600,
      espacoUnitario: 2,
      patenteMinima: 1,
      formulaDano: '1d6-1',
      multiplicadorCritico: 2,
      efeitoCritico: 'Spray descontrolado',
    ),

    // MAIS ARMAS BRANCAS
    ItemTemplate(
      nome: 'Espada Larga Medieval',
      descricao: 'Espada pesada de duas mãos, brutal.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 1500,
      espacoUnitario: 3,
      patenteMinima: 1,
      formulaDano: '1d10+2',
      multiplicadorCritico: 2,
      efeitoCritico: 'Derruba oponente',
    ),
    ItemTemplate(
      nome: 'Adaga Ritual',
      descricao: 'Punhal cerimonial afiado, usado em rituais.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 2500,
      espacoUnitario: 1,
      patenteMinima: 2,
      formulaDano: '1d4+2',
      multiplicadorCritico: 4,
      efeitoCritico: 'Sangramento mágico',
    ),
    ItemTemplate(
      nome: 'Machado de Guerra',
      descricao: 'Machado pesado de combate, devastador.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 800,
      espacoUnitario: 3,
      patenteMinima: 1,
      formulaDano: '1d10+1',
      multiplicadorCritico: 3,
    ),
    ItemTemplate(
      nome: 'Sabre de Cavalaria',
      descricao: 'Espada curva elegante e letal.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 1200,
      espacoUnitario: 2,
      patenteMinima: 1,
      formulaDano: '1d8+1',
      multiplicadorCritico: 3,
    ),
    ItemTemplate(
      nome: 'Lança de Combate',
      descricao: 'Lança com alcance estendido.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 400,
      espacoUnitario: 3,
      patenteMinima: 0,
      formulaDano: '1d8',
      multiplicadorCritico: 3,
      efeitoCritico: 'Alcance 2m',
    ),
    ItemTemplate(
      nome: 'Foice de Guerra',
      descricao: 'Foice agrícola adaptada para combate.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 300,
      espacoUnitario: 2,
      patenteMinima: 0,
      formulaDano: '1d8',
      multiplicadorCritico: 3,
    ),
    ItemTemplate(
      nome: 'Soqueira de Aço',
      descricao: 'Aumenta drasticamente o dano de socos.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 150,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaDano: '1d6',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Corrente com Espinhos',
      descricao: 'Corrente brutal que causa sangramento.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 600,
      espacoUnitario: 2,
      patenteMinima: 1,
      formulaDano: '1d8',
      multiplicadorCritico: 2,
      efeitoCritico: 'Sangramento 1d4/turno',
    ),
    ItemTemplate(
      nome: 'Nunchaku',
      descricao: 'Arma marcial oriental rápida.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 200,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaDano: '1d6',
      multiplicadorCritico: 2,
    ),
    ItemTemplate(
      nome: 'Tonfa Tática',
      descricao: 'Bastão policial de combate eficaz.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 250,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaDano: '1d6+1',
      multiplicadorCritico: 2,
    ),

    // MAIS ARCOS E OUTRAS
    ItemTemplate(
      nome: 'Arco Recurvo',
      descricao: 'Arco tradicional poderoso e silencioso.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 1200,
      espacoUnitario: 2,
      patenteMinima: 0,
      formulaDano: '1d8',
      multiplicadorCritico: 3,
    ),
    ItemTemplate(
      nome: 'Pistola de Flechas',
      descricao: 'Pequena e letal, dispara flechas curtas.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 900,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaDano: '1d6',
      multiplicadorCritico: 3,
    ),
    ItemTemplate(
      nome: 'Granada de Mão',
      descricao: 'Explosivo de fragmentação militar.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 2000,
      espacoUnitario: 1,
      patenteMinima: 2,
      formulaDano: '3d6',
      multiplicadorCritico: 2,
      efeitoCritico: 'Área 5m raio',
    ),
    ItemTemplate(
      nome: 'Granada de Fumaça',
      descricao: 'Cria cortina de fumaça densa.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 800,
      espacoUnitario: 1,
      patenteMinima: 1,
      efeitoCritico: 'Obscurece área 10m por 1min',
    ),
    ItemTemplate(
      nome: 'Granada Flash',
      descricao: 'Atordoa inimigos com luz e som.',
      tipo: ItemType.arma,
      raridade: ItemRarity.incomum,
      precoBase: 600,
      espacoUnitario: 1,
      patenteMinima: 1,
      efeitoCritico: 'Cega e ensurdece por 2 turnos',
    ),
    ItemTemplate(
      nome: 'Taser X26',
      descricao: 'Arma elétrica não-letal que incapacita.',
      tipo: ItemType.arma,
      raridade: ItemRarity.comum,
      precoBase: 1000,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaDano: '1d4',
      efeitoCritico: 'Paralisa por 1d4 turnos',
    ),
    ItemTemplate(
      nome: 'Lançador de Granadas M79',
      descricao: 'Lançador de granadas single-shot militar.',
      tipo: ItemType.arma,
      raridade: ItemRarity.lendario,
      precoBase: 18000,
      espacoUnitario: 4,
      patenteMinima: 4,
      formulaDano: '4d6',
      multiplicadorCritico: 2,
      efeitoCritico: 'Área 8m raio',
    ),
  ];

  // ========== ARMAS AMALDIÇOADAS (DA ORDEM) ==========

  static const List<ItemTemplate> armasAmaldicoadas = [
    ItemTemplate(
      nome: 'Lâmina do Vazio',
      descricao: 'Espada que corta a realidade, deixando feridas que não cicatrizam.',
      tipo: ItemType.arma,
      raridade: ItemRarity.lendario,
      precoBase: 25000,
      espacoUnitario: 2,
      patenteMinima: 4,
      nexMinimo: 65,
      isAmaldicoado: true,
      formulaDano: '2d8+4',
      multiplicadorCritico: 3,
      efeitoCritico: 'Ferida paranormal: -1d4 HP/turno por 3 turnos',
      efeitoMaldicao: 'Usuário ouve sussurros dos mortos. -1 Sanidade por combate.',
    ),
    ItemTemplate(
      nome: 'Revólver das Almas',
      descricao: 'Cada bala carrega uma alma penada que atormenta o alvo.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 18000,
      espacoUnitario: 1,
      patenteMinima: 3,
      nexMinimo: 40,
      isAmaldicoado: true,
      formulaDano: '1d10+2',
      multiplicadorCritico: 3,
      efeitoCritico: 'Alvo assombrado: -2 em testes mentais por 1 dia',
      efeitoMaldicao: 'Amaldiçoa usuário com pesadelos. -1 ponto de Sanidade ao dormir.',
    ),
    ItemTemplate(
      nome: 'Rifle do Observador',
      descricao: 'Rifle que permite ver através de paredes, mas mostra também o Outro Lado.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 22000,
      espacoUnitario: 3,
      patenteMinima: 3,
      isAmaldicoado: true,
      formulaDano: '1d8+3',
      multiplicadorCritico: 2,
      efeitoCritico: 'Ignora cobertura não-paranormal',
      efeitoMaldicao: 'Usuário vê entidades paranormais constantemente. -1 Sanidade por dia.',
    ),
    ItemTemplate(
      nome: 'Faca Sanguinária',
      descricao: 'Adaga que se alimenta de sangue, ficando mais afiada a cada morte.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 15000,
      espacoUnitario: 1,
      patenteMinima: 2,
      isAmaldicoado: true,
      formulaDano: '1d6+3',
      multiplicadorCritico: 4,
      efeitoCritico: 'Absorve vida: cura 1d4 HP do usuário',
      efeitoMaldicao: 'Exige sangue semanalmente ou causa 2d6 dano ao portador.',
    ),
    ItemTemplate(
      nome: 'Espingarda do Desespero',
      descricao: 'Dispara a própria essência do medo, paralisando inimigos.',
      tipo: ItemType.arma,
      raridade: ItemRarity.lendario,
      precoBase: 28000,
      espacoUnitario: 3,
      patenteMinima: 4,
      isAmaldicoado: true,
      formulaDano: '2d6+2',
      multiplicadorCritico: 2,
      efeitoCritico: 'Teste de Sanidade ou paralisado por 1 turno',
      efeitoMaldicao: 'Usuário sofre ataques de pânico aleatórios.',
    ),

    // MAIS ARMAS AMALDIÇOADAS
    ItemTemplate(
      nome: 'Arco das Sombras',
      descricao: 'Flechas feitas de trevas puras que drenam vida.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 16000,
      espacoUnitario: 2,
      patenteMinima: 3,
      isAmaldicoado: true,
      formulaDano: '1d8+4',
      multiplicadorCritico: 4,
      efeitoCritico: 'Drena 1d6 HP e adiciona ao usuário',
      efeitoMaldicao: 'Arma consome luz ao redor. -1 Percepção.',
    ),
    ItemTemplate(
      nome: 'Machado do Carneiro',
      descricao: 'Machado de ritual que exige sacrifícios de sangue.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 14000,
      espacoUnitario: 3,
      patenteMinima: 2,
      isAmaldicoado: true,
      formulaDano: '1d12+2',
      multiplicadorCritico: 3,
      efeitoCritico: '+2d6 se alvo já estiver ferido',
      efeitoMaldicao: 'Exige 1 HP de sacrifício antes de cada uso.',
    ),
    ItemTemplate(
      nome: 'Pistola Fantasma',
      descricao: 'Arma que dispara balas espectrais intangíveis.',
      tipo: ItemType.arma,
      raridade: ItemRarity.lendario,
      precoBase: 20000,
      espacoUnitario: 1,
      patenteMinima: 3,
      isAmaldicoado: true,
      formulaDano: '1d8+3',
      multiplicadorCritico: 3,
      efeitoCritico: 'Ignora armadura física',
      efeitoMaldicao: 'Usuário gradualmente perde solidez. -1 Vigor.',
    ),
    ItemTemplate(
      nome: 'Lança do Martírio',
      descricao: 'Quanto mais o usuário sofre, mais poderosa fica.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 12000,
      espacoUnitario: 3,
      patenteMinima: 2,
      isAmaldicoado: true,
      formulaDano: '1d10',
      multiplicadorCritico: 2,
      efeitoCritico: '+1d6 para cada 10 HP perdido',
      efeitoMaldicao: 'Usuário sente dor de feridas antigas.',
    ),
    ItemTemplate(
      nome: 'Cimitarra Eterna',
      descricao: 'Espada que prende almas no fio da lâmina.',
      tipo: ItemType.arma,
      raridade: ItemRarity.lendario,
      precoBase: 24000,
      espacoUnitario: 2,
      patenteMinima: 4,
      isAmaldicoado: true,
      formulaDano: '1d10+3',
      multiplicadorCritico: 3,
      efeitoCritico: 'Mata instantaneamente se crítico e alvo < 20 HP',
      efeitoMaldicao: 'Almas presas lamentam constantemente. -2 Sanidade/dia.',
    ),
    ItemTemplate(
      nome: 'Fuzil da Verdade',
      descricao: 'Sempre acerta, mas revela segredos terríveis.',
      tipo: ItemType.arma,
      raridade: ItemRarity.lendario,
      precoBase: 26000,
      espacoUnitario: 3,
      patenteMinima: 4,
      isAmaldicoado: true,
      formulaDano: '2d6+3',
      multiplicadorCritico: 2,
      efeitoCritico: '+10 acerto automático',
      efeitoMaldicao: 'Revela verdades que não devem ser conhecidas.',
    ),
    ItemTemplate(
      nome: 'Garrote da Traição',
      descricao: 'Corrente que se aperta sozinha no pescoço do alvo.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 11000,
      espacoUnitario: 1,
      patenteMinima: 2,
      isAmaldicoado: true,
      formulaDano: '1d6+2',
      multiplicadorCritico: 4,
      efeitoCritico: 'Estrangula: 2d6/turno por 3 turnos',
      efeitoMaldicao: 'Usuário trai aliados involuntariamente.',
    ),
    ItemTemplate(
      nome: 'Martelo do Julgamento',
      descricao: 'Julga e executa os pecadores com força divina corrupta.',
      tipo: ItemType.arma,
      raridade: ItemRarity.lendario,
      precoBase: 22000,
      espacoUnitario: 4,
      patenteMinima: 3,
      isAmaldicoado: true,
      formulaDano: '2d8+2',
      multiplicadorCritico: 3,
      efeitoCritico: 'Dano dobrado contra "pecadores"',
      efeitoMaldicao: 'Usuário se torna fanático e julga todos.',
    ),
    ItemTemplate(
      nome: 'Shuriken do Destino',
      descricao: 'Retorna sempre para o dono, mas nunca esquece sangue.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 13000,
      espacoUnitario: 1,
      patenteMinima: 2,
      isAmaldicoado: true,
      formulaDano: '1d6+3',
      multiplicadorCritico: 4,
      efeitoCritico: 'Retorna e ataca novamente',
      efeitoMaldicao: 'Pode atacar o próprio usuário se errar.',
    ),
    ItemTemplate(
      nome: 'Chicote de Almas',
      descricao: 'Feito de cordas de cabelo de mortos, arranca a alma.',
      tipo: ItemType.arma,
      raridade: ItemRarity.raro,
      precoBase: 15000,
      espacoUnitario: 2,
      patenteMinima: 3,
      isAmaldicoado: true,
      formulaDano: '1d8+2',
      multiplicadorCritico: 2,
      efeitoCritico: 'Arranca fragmento da alma: -1d4 PE',
      efeitoMaldicao: 'Mortos sussurram ao usuário.',
    ),
  ];

  // ========== CURAS ==========

  static const List<ItemTemplate> curas = [
    // Kits médicos
    ItemTemplate(
      nome: 'Kit de Primeiros Socorros',
      descricao: 'Bandagens, anti-sépticos e materiais básicos de emergência.',
      tipo: ItemType.cura,
      raridade: ItemRarity.comum,
      precoBase: 150,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d6+2',
    ),
    ItemTemplate(
      nome: 'Kit Médico Avançado',
      descricao: 'Equipamento profissional com sutura, analgésicos e instrumentos.',
      tipo: ItemType.cura,
      raridade: ItemRarity.incomum,
      precoBase: 800,
      espacoUnitario: 2,
      patenteMinima: 1,
      formulaCura: '2d6+4',
      efeitoAdicional: 'Estanca sangramento',
    ),
    ItemTemplate(
      nome: 'Kit Cirúrgico de Campo',
      descricao: 'Permite procedimentos complexos em condições adversas.',
      tipo: ItemType.cura,
      raridade: ItemRarity.raro,
      precoBase: 2500,
      espacoUnitario: 3,
      patenteMinima: 2,
      formulaCura: '3d6+6',
      buffTipo: BuffType.estancarSangramento,
      buffDescricao: 'Para qualquer sangramento',
      buffDuracao: BuffDuration.instantaneo,
    ),

    // Medicamentos
    ItemTemplate(
      nome: 'Analgésico Forte',
      descricao: 'Reduz dor severa, permitindo continuar em ação.',
      tipo: ItemType.cura,
      raridade: ItemRarity.comum,
      precoBase: 80,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4',
      buffTipo: BuffType.aumentarVigor,
      buffDescricao: 'Ignora penalidades de dor',
      buffDuracao: BuffDuration.combate,
      buffValor: 2,
    ),
    ItemTemplate(
      nome: 'Adrenalina Sintética',
      descricao: 'Injeção que revitaliza instantaneamente em situações críticas.',
      tipo: ItemType.cura,
      raridade: ItemRarity.incomum,
      precoBase: 500,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaCura: '2d4+2',
      buffTipo: BuffType.aumentarVelocidade,
      buffDescricao: '+3m movimento por 3 turnos',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 3,
      buffValor: 3,
    ),
    ItemTemplate(
      nome: 'Estimulante Militar',
      descricao: 'Usado em zonas de combate para manter soldados alertas.',
      tipo: ItemType.cura,
      raridade: ItemRarity.incomum,
      precoBase: 400,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaCura: '0',
      buffTipo: BuffType.aumentarPresenca,
      buffDescricao: '+2 Presença e Percepção',
      buffDuracao: BuffDuration.combate,
      buffValor: 2,
    ),

    // Poções/Elixires
    ItemTemplate(
      nome: 'Elixir de Vitalidade',
      descricao: 'Líquido dourado que restaura vigor e energia vital.',
      tipo: ItemType.cura,
      raridade: ItemRarity.raro,
      precoBase: 1500,
      espacoUnitario: 1,
      patenteMinima: 2,
      formulaCura: '3d6+4',
    ),
    ItemTemplate(
      nome: 'Tônico Restaurador',
      descricao: 'Cura feridas e doenças menores rapidamente.',
      tipo: ItemType.cura,
      raridade: ItemRarity.comum,
      precoBase: 200,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d6+1',
      buffTipo: BuffType.removerDoenca,
      buffDescricao: 'Remove doenças comuns',
      buffDuracao: BuffDuration.instantaneo,
    ),
    ItemTemplate(
      nome: 'Antídoto Universal',
      descricao: 'Neutraliza a maioria dos venenos conhecidos.',
      tipo: ItemType.cura,
      raridade: ItemRarity.incomum,
      precoBase: 600,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaCura: '1d4',
      buffTipo: BuffType.removerVeneno,
      buffDescricao: 'Remove venenos',
      buffDuracao: BuffDuration.instantaneo,
    ),
    ItemTemplate(
      nome: 'Poção de Regeneração',
      descricao: 'Líquido mágico que estimula regeneração celular acelerada.',
      tipo: ItemType.cura,
      raridade: ItemRarity.lendario,
      precoBase: 5000,
      espacoUnitario: 1,
      patenteMinima: 3,
      formulaCura: '4d6+8',
      buffTipo: BuffType.regeneracao,
      buffDescricao: 'Regenera 1d4 HP por turno',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 5,
      buffValor: 1,
    ),

    // Especiais
    ItemTemplate(
      nome: 'Desfibrilador Portátil',
      descricao: 'Pode reviver personagem recém-morto (menos de 1 minuto).',
      tipo: ItemType.cura,
      raridade: ItemRarity.raro,
      precoBase: 3000,
      espacoUnitario: 2,
      patenteMinima: 2,
      formulaCura: '1d6',
      buffTipo: BuffType.reviver,
      buffDescricao: 'Revive com 1 HP se morto há menos de 1 minuto',
      buffDuracao: BuffDuration.instantaneo,
    ),

    // MAIS MEDICAMENTOS E CURAS
    ItemTemplate(
      nome: 'Morfina Militar',
      descricao: 'Analgésico potente para ferimentos graves.',
      tipo: ItemType.cura,
      raridade: ItemRarity.incomum,
      precoBase: 350,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaCura: '1d6+2',
      buffTipo: BuffType.aumentarVigor,
      buffDescricao: 'Remove penalidades de dor',
      buffDuracao: BuffDuration.combate,
      buffValor: 3,
    ),
    ItemTemplate(
      nome: 'Soro Fisiológico',
      descricao: 'Hidratação intravenosa rápida.',
      tipo: ItemType.cura,
      raridade: ItemRarity.comum,
      precoBase: 120,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4+1',
    ),
    ItemTemplate(
      nome: 'Antibiótico de Amplo Espectro',
      descricao: 'Combate infecções bacterianas.',
      tipo: ItemType.cura,
      raridade: ItemRarity.comum,
      precoBase: 180,
      espacoUnitario: 1,
      patenteMinima: 0,
      buffTipo: BuffType.removerDoenca,
      buffDescricao: 'Remove infecções',
      buffDuracao: BuffDuration.instantaneo,
    ),
    ItemTemplate(
      nome: 'Plasma Sintético',
      descricao: 'Substituto de sangue de emergência.',
      tipo: ItemType.cura,
      raridade: ItemRarity.raro,
      precoBase: 2000,
      espacoUnitario: 2,
      patenteMinima: 2,
      formulaCura: '2d6+6',
      buffTipo: BuffType.estancarSangramento,
      buffDescricao: 'Para sangramento severo',
      buffDuracao: BuffDuration.instantaneo,
    ),
    ItemTemplate(
      nome: 'Injeção de Epinefrina',
      descricao: 'Adrenalina pura para emergências cardíacas.',
      tipo: ItemType.cura,
      raridade: ItemRarity.incomum,
      precoBase: 450,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaCura: '1d4+2',
      buffTipo: BuffType.aumentarVelocidade,
      buffDescricao: '+5m movimento',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 4,
      buffValor: 5,
    ),
    ItemTemplate(
      nome: 'Gel Cicatrizante',
      descricao: 'Gel moderno que acelera cicatrização.',
      tipo: ItemType.cura,
      raridade: ItemRarity.incomum,
      precoBase: 600,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaCura: '2d4+2',
      buffTipo: BuffType.regeneracao,
      buffDescricao: 'Regenera 1d4 HP/turno',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 3,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Tranquilizante',
      descricao: 'Acalma e reduz estresse severo.',
      tipo: ItemType.cura,
      raridade: ItemRarity.comum,
      precoBase: 200,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '0',
      buffTipo: BuffType.aumentarPresenca,
      buffDescricao: 'Remove pânico e medo',
      buffDuracao: BuffDuration.combate,
      buffValor: 2,
    ),
    ItemTemplate(
      nome: 'Nanobots Médicos',
      descricao: 'Tecnologia experimental de cura automática.',
      tipo: ItemType.cura,
      raridade: ItemRarity.lendario,
      precoBase: 8000,
      espacoUnitario: 1,
      patenteMinima: 4,
      formulaCura: '5d6+10',
      buffTipo: BuffType.regeneracao,
      buffDescricao: 'Regenera 2d4 HP/turno',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 5,
      buffValor: 2,
    ),
    ItemTemplate(
      nome: 'Curativo de Combate QuikClot',
      descricao: 'Agente coagulante militar de emergência.',
      tipo: ItemType.cura,
      raridade: ItemRarity.incomum,
      precoBase: 300,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaCura: '1d6',
      buffTipo: BuffType.estancarSangramento,
      buffDescricao: 'Para sangramento imediato',
      buffDuracao: BuffDuration.instantaneo,
    ),
    ItemTemplate(
      nome: 'Inalador de Oxigênio',
      descricao: 'Oxigênio puro concentrado.',
      tipo: ItemType.cura,
      raridade: ItemRarity.comum,
      precoBase: 150,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4',
      buffTipo: BuffType.aumentarVigor,
      buffDescricao: '+1 Vigor temporário',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 5,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Cápsula de Recuperação Rápida',
      descricao: 'Coquetel de vitaminas e minerais.',
      tipo: ItemType.cura,
      raridade: ItemRarity.comum,
      precoBase: 100,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d6',
    ),
    ItemTemplate(
      nome: 'Soro Anti-Radiação',
      descricao: 'Protege contra envenenamento por radiação.',
      tipo: ItemType.cura,
      raridade: ItemRarity.raro,
      precoBase: 1800,
      espacoUnitario: 1,
      patenteMinima: 2,
      formulaCura: '1d6+1',
      buffTipo: BuffType.removerVeneno,
      buffDescricao: 'Remove radiação',
      buffDuracao: BuffDuration.instantaneo,
    ),
    ItemTemplate(
      nome: 'Kit de Sutura Avançado',
      descricao: 'Para fechar ferimentos profundos rapidamente.',
      tipo: ItemType.cura,
      raridade: ItemRarity.incomum,
      precoBase: 500,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaCura: '2d4+3',
    ),
    ItemTemplate(
      nome: 'Benzodiazepínico',
      descricao: 'Medicamento para ataques de ansiedade.',
      tipo: ItemType.cura,
      raridade: ItemRarity.comum,
      precoBase: 90,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '0',
      buffTipo: BuffType.aumentarPresenca,
      buffDescricao: 'Reduz ansiedade',
      buffDuracao: BuffDuration.combate,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Bolsa de Gelo Instantâneo',
      descricao: 'Reduz inchaço e inflamação.',
      tipo: ItemType.cura,
      raridade: ItemRarity.comum,
      precoBase: 50,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4',
    ),
    ItemTemplate(
      nome: 'Compressa Térmica',
      descricao: 'Alivia dores musculares.',
      tipo: ItemType.cura,
      raridade: ItemRarity.comum,
      precoBase: 40,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4',
    ),
    ItemTemplate(
      nome: 'Hemostático em Pó',
      descricao: 'Pó que para hemorragias instantaneamente.',
      tipo: ItemType.cura,
      raridade: ItemRarity.incomum,
      precoBase: 400,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaCura: '1d6',
      buffTipo: BuffType.estancarSangramento,
      buffDescricao: 'Para hemorragia',
      buffDuracao: BuffDuration.instantaneo,
    ),
    ItemTemplate(
      nome: 'Spray Anestésico',
      descricao: 'Anestesia tópica para procedimentos.',
      tipo: ItemType.cura,
      raridade: ItemRarity.comum,
      precoBase: 140,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4',
      buffTipo: BuffType.aumentarVigor,
      buffDescricao: 'Remove dor localizada',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 3,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Sangue Tipo O Negativo',
      descricao: 'Doador universal para transfusões.',
      tipo: ItemType.cura,
      raridade: ItemRarity.raro,
      precoBase: 1500,
      espacoUnitario: 2,
      patenteMinima: 2,
      formulaCura: '3d6+4',
    ),
    ItemTemplate(
      nome: 'Pílula de Combate Modafinil',
      descricao: 'Mantém alerta por 24 horas.',
      tipo: ItemType.cura,
      raridade: ItemRarity.incomum,
      precoBase: 300,
      espacoUnitario: 1,
      patenteMinima: 1,
      formulaCura: '0',
      buffTipo: BuffType.aumentarPresenca,
      buffDescricao: 'Remove sono e fadiga',
      buffDuracao: BuffDuration.combate,
      buffValor: 2,
    ),
  ];

  // ========== CURAS AMALDIÇOADAS (DA ORDEM) ==========

  static const List<ItemTemplate> curasAmaldicoadas = [
    ItemTemplate(
      nome: 'Cicatrizante Temporal',
      descricao: 'Cura instantânea mas rouba anos de vida.',
      tipo: ItemType.cura,
      raridade: ItemRarity.raro,
      precoBase: 10000,
      espacoUnitario: 1,
      patenteMinima: 3,
      isAmaldicoado: true,
      formulaCura: '4d6+10',
      buffTipo: BuffType.envelhecer,
      buffDescricao: 'Envelhece 2d6 anos',
      buffDuracao: BuffDuration.permanente,
      buffValor: 2,
      efeitoMaldicao: 'Usuário envelhece permanentemente.',
    ),
    ItemTemplate(
      nome: 'Soro da Dor Alheia',
      descricao: 'Transfere ferimentos para outra pessoa próxima.',
      tipo: ItemType.cura,
      raridade: ItemRarity.lendario,
      precoBase: 15000,
      espacoUnitario: 1,
      patenteMinima: 4,
      isAmaldicoado: true,
      formulaCura: 'TOTAL',
      efeitoMaldicao: 'Transfere todo dano curado para aliado mais próximo.',
    ),
    ItemTemplate(
      nome: 'Elixir da Lucidez Cruel',
      descricao: 'Cura mente mas revela verdades aterrorizantes.',
      tipo: ItemType.cura,
      raridade: ItemRarity.raro,
      precoBase: 8000,
      espacoUnitario: 1,
      patenteMinima: 2,
      isAmaldicoado: true,
      formulaCura: '0',
      buffTipo: BuffType.aumentarInteligencia,
      buffDescricao: '+4 Inteligência',
      buffDuracao: BuffDuration.combate,
      buffValor: 4,
      efeitoMaldicao: 'Usuário vê a verdade sobre o universo. Teste de Sanidade.',
    ),
    ItemTemplate(
      nome: 'Tônico do Esquecimento',
      descricao: 'Cura traumas mentais mas apaga memórias importantes.',
      tipo: ItemType.cura,
      raridade: ItemRarity.incomum,
      precoBase: 3000,
      espacoUnitario: 1,
      patenteMinima: 1,
      isAmaldicoado: true,
      formulaCura: '2d6',
      buffTipo: BuffType.confusao,
      buffDescricao: 'Esquece eventos recentes',
      buffDuracao: BuffDuration.permanente,
      efeitoMaldicao: 'Apaga memórias das últimas 24 horas.',
    ),
  ];

  // ========== COMIDAS ==========

  static const List<ItemTemplate> comidas = [
    // Lanches
    ItemTemplate(
      nome: 'Barra de Cereal',
      descricao: 'Lanche rápido e nutritivo para emergências.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 15,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4',
    ),
    ItemTemplate(
      nome: 'Chocolate',
      descricao: 'Doce que levanta o ânimo em situações difíceis.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 20,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1',
      buffTipo: BuffType.aumentarPresenca,
      buffDescricao: '+1 moral temporário',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 2,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Sanduíche',
      descricao: 'Refeição simples mas satisfatória.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 30,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4+1',
    ),
    ItemTemplate(
      nome: 'Pizza Congelada',
      descricao: 'Comfort food que restaura energia e moral.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 40,
      espacoUnitario: 2,
      patenteMinima: 0,
      formulaCura: '1d6',
    ),

    // Bebidas
    ItemTemplate(
      nome: 'Água Mineral',
      descricao: 'Hidratação essencial.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 10,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1',
    ),
    ItemTemplate(
      nome: 'Energético',
      descricao: 'Bebida que aumenta energia temporariamente.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 25,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '0',
      buffTipo: BuffType.aumentarVigor,
      buffDescricao: '+1 Vigor temporário',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 4,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Café Forte',
      descricao: 'Mantém acordado e alerta por horas.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 15,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '0',
      buffTipo: BuffType.aumentarPresenca,
      buffDescricao: 'Remove fadiga',
      buffDuracao: BuffDuration.combate,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Refrigerante',
      descricao: 'Bebida doce e refrescante.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 12,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1',
    ),

    // Refeições
    ItemTemplate(
      nome: 'Ração Militar (MRE)',
      descricao: 'Refeição completa de combate, alta em calorias.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 80,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d6+2',
      buffTipo: BuffType.aumentarVigor,
      buffDescricao: '+1 Vigor por 4 horas',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 8,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Comida Caseira',
      descricao: 'Refeição feita com carinho, reconfortante.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.incomum,
      precoBase: 50,
      espacoUnitario: 2,
      patenteMinima: 0,
      formulaCura: '2d4+2',
      buffTipo: BuffType.aumentarPresenca,
      buffDescricao: 'Remove estresse, +2 moral',
      buffDuracao: BuffDuration.combate,
      buffValor: 2,
    ),

    // MAIS COMIDAS
    ItemTemplate(
      nome: 'Suco de Laranja',
      descricao: 'Vitamina C pura e refrescante.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 18,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4',
    ),
    ItemTemplate(
      nome: 'Salgadinho',
      descricao: 'Snack salgado crocante.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 12,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1',
    ),
    ItemTemplate(
      nome: 'Biscoito Proteico',
      descricao: 'Alto valor nutritivo, ideal para missões.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 25,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4+1',
    ),
    ItemTemplate(
      nome: 'Smoothie de Frutas',
      descricao: 'Vitaminas naturais e energia rápida.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 35,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d6',
      buffTipo: BuffType.aumentarVigor,
      buffDescricao: '+1 Vigor temporário',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 3,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Macarrão Instantâneo',
      descricao: 'Rápido e fácil de preparar.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 8,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4',
    ),
    ItemTemplate(
      nome: 'Hambúrguer',
      descricao: 'Fast food reconfortante.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 45,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d6+1',
    ),
    ItemTemplate(
      nome: 'Taco Mexicano',
      descricao: 'Picante e saboroso.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 35,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4+2',
    ),
    ItemTemplate(
      nome: 'Sopa Enlatada',
      descricao: 'Quente e nutritiva.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 22,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d6',
    ),
    ItemTemplate(
      nome: 'Churrasco',
      descricao: 'Carne grelhada suculenta.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.incomum,
      precoBase: 80,
      espacoUnitario: 2,
      patenteMinima: 0,
      formulaCura: '2d4+2',
      buffTipo: BuffType.aumentarVigor,
      buffDescricao: '+2 Vigor',
      buffDuracao: BuffDuration.combate,
      buffValor: 2,
    ),
    ItemTemplate(
      nome: 'Sushi',
      descricao: 'Peixe fresco e arroz, leve e nutritivo.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.incomum,
      precoBase: 60,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d6+2',
    ),
    ItemTemplate(
      nome: 'Proteína em Pó (Shake)',
      descricao: 'Alta proteína para recuperação muscular.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 45,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4',
      buffTipo: BuffType.aumentarVigor,
      buffDescricao: '+1 Vigor',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 5,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Isotônico',
      descricao: 'Repõe eletrólitos perdidos.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 20,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4',
    ),
    ItemTemplate(
      nome: 'Barrinha de Proteína',
      descricao: 'Energia compacta para atletas.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 28,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4+1',
    ),
    ItemTemplate(
      nome: 'Pudim',
      descricao: 'Sobremesa doce que levanta o ânimo.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 15,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4',
      buffTipo: BuffType.aumentarPresenca,
      buffDescricao: '+1 moral',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 2,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Whisky',
      descricao: 'Bebida forte que aquece.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 55,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1',
      buffTipo: BuffType.aumentarPresenca,
      buffDescricao: '+1 coragem temporária',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 3,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Vinho Tinto',
      descricao: 'Bebida refinada que relaxa.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 40,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1',
      buffTipo: BuffType.aumentarPresenca,
      buffDescricao: 'Relaxa',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 2,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Cerveja Gelada',
      descricao: 'Refrescante e descontraída.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 18,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1',
    ),
    ItemTemplate(
      nome: 'Torta de Maçã',
      descricao: 'Doce caseira reconfortante.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 32,
      espacoUnitario: 2,
      patenteMinima: 0,
      formulaCura: '1d6',
      buffTipo: BuffType.aumentarPresenca,
      buffDescricao: 'Conforto',
      buffDuracao: BuffDuration.turnos,
      buffTurnos: 3,
      buffValor: 1,
    ),
    ItemTemplate(
      nome: 'Frutas Frescas',
      descricao: 'Saudável e natural.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 25,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4+1',
    ),
    ItemTemplate(
      nome: 'Chá Verde',
      descricao: 'Antioxidante natural.',
      tipo: ItemType.consumivel,
      raridade: ItemRarity.comum,
      precoBase: 14,
      espacoUnitario: 1,
      patenteMinima: 0,
      formulaCura: '1d4',
    ),
  ];

  // ========== UTILIDADES (ITENS CIVIS) ==========

  static const List<ItemTemplate> utilidades = [
    ItemTemplate(
      nome: 'Lanterna Tática',
      descricao: 'Lanterna militar de alto lúmen com modo estroboscópico.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 200,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Relógio Multifunção',
      descricao: 'Relógio com GPS, bússola e cronômetro.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 500,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Corda de Escalada (20m)',
      descricao: 'Corda resistente para escalada e resgate.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 150,
      espacoUnitario: 2,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Kit de Ferramentas',
      descricao: 'Ferramentas básicas para reparos e improvisação.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 300,
      espacoUnitario: 2,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Binóculo Tático',
      descricao: 'Binóculo militar com visão noturna integrada.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 1200,
      espacoUnitario: 1,
      patenteMinima: 1,
      buffTipo: BuffType.visaoNoturna,
      buffDescricao: 'Permite ver no escuro',
      buffDuracao: BuffDuration.combate,
    ),
    ItemTemplate(
      nome: 'Walkie-Talkie',
      descricao: 'Rádio de comunicação de médio alcance.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 250,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Lockpicks Profissionais',
      descricao: 'Kit de gazuas para arrombamento.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 400,
      espacoUnitario: 1,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Câmera de Vigilância',
      descricao: 'Câmera pequena com transmissão sem fio.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 600,
      espacoUnitario: 1,
      patenteMinima: 1,
    ),

    // MAIS UTILIDADES
    ItemTemplate(
      nome: 'GPS Tático',
      descricao: 'GPS militar de alta precisão.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 800,
      espacoUnitario: 1,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Detector de Movimento',
      descricao: 'Alarme portátil que detecta movimentos.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 700,
      espacoUnitario: 1,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Kit de Sobrevivência',
      descricao: 'Itens essenciais para sobreviver na selva.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 350,
      espacoUnitario: 2,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Mochila Tática 40L',
      descricao: 'Mochila militar resistente.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 180,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Saco de Dormir Térmico',
      descricao: 'Protege contra frio extremo.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 150,
      espacoUnitario: 2,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Barraca Individual',
      descricao: 'Abrigo leve e compacto.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 200,
      espacoUnitario: 2,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Filtro de Água Portátil',
      descricao: 'Purifica água de qualquer fonte.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 120,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Isqueiro à Prova d\'Água',
      descricao: 'Funciona mesmo molhado.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 45,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Apito de Emergência',
      descricao: 'Som alto para chamar atenção.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 20,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Espelho de Sinalização',
      descricao: 'Reflete luz solar para sinalização.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 30,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Fita Adesiva Reforçada',
      descricao: 'Resolve quase qualquer problema.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 35,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Canivete Multiuso',
      descricao: 'Ferramenta versátil para múltiplas tarefas.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 90,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Óculos de Visão Noturna',
      descricao: 'Permite ver no escuro completo.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.raro,
      precoBase: 2500,
      espacoUnitario: 1,
      patenteMinima: 2,
      buffTipo: BuffType.visaoNoturna,
      buffDescricao: 'Visão no escuro',
      buffDuracao: BuffDuration.combate,
    ),
    ItemTemplate(
      nome: 'Detector de Metais',
      descricao: 'Localiza objetos metálicos enterrados.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 550,
      espacoUnitario: 2,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Medidor Geiger',
      descricao: 'Detecta radiação.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.raro,
      precoBase: 1800,
      espacoUnitario: 1,
      patenteMinima: 2,
    ),
    ItemTemplate(
      nome: 'Drone de Reconhecimento',
      descricao: 'Pequeno drone com câmera.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.raro,
      precoBase: 3500,
      espacoUnitario: 2,
      patenteMinima: 2,
    ),
    ItemTemplate(
      nome: 'Microfone Direcional',
      descricao: 'Escuta conversas à distância.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 900,
      espacoUnitario: 1,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Jammer de Sinal',
      descricao: 'Bloqueia comunicações eletrônicas.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.raro,
      precoBase: 2200,
      espacoUnitario: 2,
      patenteMinima: 2,
    ),
    ItemTemplate(
      nome: 'Laptop Criptografado',
      descricao: 'Computador seguro contra hackers.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 2800,
      espacoUnitario: 2,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Tablet Militar Ruggedizado',
      descricao: 'Resistente a água, quedas e poeira.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 1500,
      espacoUnitario: 1,
      patenteMinima: 1,
    ),
  ];

  // ========== MUNIÇÕES ==========

  static const List<ItemTemplate> municoes = [
    ItemTemplate(
      nome: 'Munição 9mm (50 un)',
      descricao: 'Munição padrão para pistolas.',
      tipo: ItemType.municao,
      raridade: ItemRarity.comum,
      precoBase: 80,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Munição .45 ACP (50 un)',
      descricao: 'Munição de alto calibre.',
      tipo: ItemType.municao,
      raridade: ItemRarity.comum,
      precoBase: 100,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Munição 5.56mm (100 un)',
      descricao: 'Munição padrão para rifles de assalto.',
      tipo: ItemType.municao,
      raridade: ItemRarity.comum,
      precoBase: 200,
      espacoUnitario: 2,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Munição 12 GA (25 un)',
      descricao: 'Cartuchos para espingarda.',
      tipo: ItemType.municao,
      raridade: ItemRarity.comum,
      precoBase: 120,
      espacoUnitario: 2,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Munição .50 BMG (20 un)',
      descricao: 'Munição anti-material de altíssimo calibre.',
      tipo: ItemType.municao,
      raridade: ItemRarity.raro,
      precoBase: 800,
      espacoUnitario: 2,
      patenteMinima: 3,
    ),

    // MAIS MUNIÇÕES
    ItemTemplate(
      nome: 'Munição .357 Magnum (50 un)',
      descricao: 'Munição poderosa para revólveres.',
      tipo: ItemType.municao,
      raridade: ItemRarity.comum,
      precoBase: 110,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Munição .308 Winchester (50 un)',
      descricao: 'Munição de precisão para rifles.',
      tipo: ItemType.municao,
      raridade: ItemRarity.incomum,
      precoBase: 180,
      espacoUnitario: 2,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Munição 7.62mm (100 un)',
      descricao: 'Munição soviética para AK e similares.',
      tipo: ItemType.municao,
      raridade: ItemRarity.comum,
      precoBase: 190,
      espacoUnitario: 2,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Munição .22 LR (100 un)',
      descricao: 'Munição leve de baixo calibre.',
      tipo: ItemType.municao,
      raridade: ItemRarity.comum,
      precoBase: 50,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Munição .44 Magnum (50 un)',
      descricao: 'Munição extremamente poderosa.',
      tipo: ItemType.municao,
      raridade: ItemRarity.incomum,
      precoBase: 140,
      espacoUnitario: 1,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Flechas (12 un)',
      descricao: 'Flechas para arcos e bestas.',
      tipo: ItemType.municao,
      raridade: ItemRarity.comum,
      precoBase: 60,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Virotes de Besta (20 un)',
      descricao: 'Virotes curtos para bestas.',
      tipo: ItemType.municao,
      raridade: ItemRarity.comum,
      precoBase: 80,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Munição Subsônica 9mm (50 un)',
      descricao: 'Munição silenciosa para operações furtivas.',
      tipo: ItemType.municao,
      raridade: ItemRarity.incomum,
      precoBase: 150,
      espacoUnitario: 1,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Munição Perfurante .338 Lapua (20 un)',
      descricao: 'Munição de precisão extrema para atiradores de elite.',
      tipo: ItemType.municao,
      raridade: ItemRarity.raro,
      precoBase: 600,
      espacoUnitario: 2,
      patenteMinima: 3,
    ),
    ItemTemplate(
      nome: 'Munição Incendiária 12 GA (10 un)',
      descricao: 'Cartuchos que causam ignição.',
      tipo: ItemType.municao,
      raridade: ItemRarity.raro,
      precoBase: 400,
      espacoUnitario: 2,
      patenteMinima: 2,
    ),
    ItemTemplate(
      nome: 'Slugs 12 GA (25 un)',
      descricao: 'Projéteis únicos para espingarda, alta penetração.',
      tipo: ItemType.municao,
      raridade: ItemRarity.incomum,
      precoBase: 160,
      espacoUnitario: 2,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Munição Traçante 5.56mm (50 un)',
      descricao: 'Munição que deixa rastro luminoso.',
      tipo: ItemType.municao,
      raridade: ItemRarity.incomum,
      precoBase: 250,
      espacoUnitario: 2,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Munição Hollow Point .45 (50 un)',
      descricao: 'Munição expansiva de alto dano.',
      tipo: ItemType.municao,
      raridade: ItemRarity.incomum,
      precoBase: 130,
      espacoUnitario: 1,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Munição Blindada 7.62mm (50 un)',
      descricao: 'Perfura coletes balísticos.',
      tipo: ItemType.municao,
      raridade: ItemRarity.raro,
      precoBase: 350,
      espacoUnitario: 2,
      patenteMinima: 2,
    ),
  ];

  // ========== EQUIPAMENTOS/ARMADURAS ==========

  static const List<ItemTemplate> equipamentos = [
    ItemTemplate(
      nome: 'Colete Tático Leve',
      descricao: 'Proteção balística nível II, permite mobilidade.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 2000,
      espacoUnitario: 3,
      patenteMinima: 1,
      defesaBonus: 2,
    ),
    ItemTemplate(
      nome: 'Colete Tático Pesado',
      descricao: 'Proteção balística nível IV, máxima defesa.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 5000,
      espacoUnitario: 5,
      patenteMinima: 2,
      defesaBonus: 4,
    ),
    ItemTemplate(
      nome: 'Capacete Balístico',
      descricao: 'Protege cabeça de projéteis e fragmentos.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 800,
      espacoUnitario: 1,
      patenteMinima: 1,
      defesaBonus: 1,
    ),
    ItemTemplate(
      nome: 'Escudo Tático',
      descricao: 'Escudo balístico para proteção em avanço.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 3000,
      espacoUnitario: 4,
      patenteMinima: 2,
      defesaBonus: 3,
    ),
    ItemTemplate(
      nome: 'Armadura Paranormal',
      descricao: 'Armadura da Ordem inscrita com runas protetoras.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.lendario,
      precoBase: 15000,
      espacoUnitario: 4,
      patenteMinima: 4,
      defesaBonus: 5,
      buffTipo: BuffType.resistenciaParanormal,
      buffDescricao: '+3 resistência paranormal',
      buffDuracao: BuffDuration.permanente,
      buffValor: 3,
    ),

    // MAIS EQUIPAMENTOS
    ItemTemplate(
      nome: 'Colete Discreto',
      descricao: 'Proteção balística escondida sob roupas.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 2800,
      espacoUnitario: 2,
      patenteMinima: 1,
      defesaBonus: 2,
    ),
    ItemTemplate(
      nome: 'Joelheiras e Cotoveleiras Táticas',
      descricao: 'Proteção para articulações em combate.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 200,
      espacoUnitario: 1,
      patenteMinima: 0,
      defesaBonus: 1,
    ),
    ItemTemplate(
      nome: 'Luvas Táticas Reforçadas',
      descricao: 'Protege mãos e melhora aderência.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 120,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Botas de Combate',
      descricao: 'Botas resistentes para terrenos difíceis.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 250,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Máscara de Gás',
      descricao: 'Protege contra agentes químicos e biológicos.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 600,
      espacoUnitario: 1,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Óculos Balísticos',
      descricao: 'Protege olhos de fragmentos e estilhaços.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 150,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Cinto Tático com Coldres',
      descricao: 'Organiza equipamento e armas.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 180,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Colete Porta-Placas',
      descricao: 'Aceita placas balísticas customizadas.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 3500,
      espacoUnitario: 4,
      patenteMinima: 2,
      defesaBonus: 3,
    ),
    ItemTemplate(
      nome: 'Placa Balística Nível IV',
      descricao: 'Placa de proteção máxima.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.raro,
      precoBase: 2000,
      espacoUnitario: 2,
      patenteMinima: 2,
      defesaBonus: 2,
    ),
    ItemTemplate(
      nome: 'Armadura Completa SWAT',
      descricao: 'Conjunto completo de proteção tática.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.raro,
      precoBase: 8000,
      espacoUnitario: 6,
      patenteMinima: 3,
      defesaBonus: 5,
    ),
    ItemTemplate(
      nome: 'Exoesqueleto de Combate',
      descricao: 'Tecnologia experimental que aumenta força.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.lendario,
      precoBase: 25000,
      espacoUnitario: 8,
      patenteMinima: 5,
      defesaBonus: 4,
      buffTipo: BuffType.aumentarForca,
      buffDescricao: '+3 Força',
      buffDuracao: BuffDuration.permanente,
      buffValor: 3,
    ),
    ItemTemplate(
      nome: 'Traje Anti-Radiação',
      descricao: 'Proteção total contra radiação.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.raro,
      precoBase: 4500,
      espacoUnitario: 5,
      patenteMinima: 2,
      defesaBonus: 2,
    ),
    ItemTemplate(
      nome: 'Traje Hazmat',
      descricao: 'Proteção contra materiais perigosos.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 1200,
      espacoUnitario: 3,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Capa de Camuflagem Óptica',
      descricao: 'Tecnologia que dificulta detecção visual.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.lendario,
      precoBase: 20000,
      espacoUnitario: 2,
      patenteMinima: 4,
      buffTipo: BuffType.invisibilidade,
      buffDescricao: 'Camuflagem ativa',
      buffDuracao: BuffDuration.combate,
    ),
    ItemTemplate(
      nome: 'Paraquedas Tático',
      descricao: 'Para infiltrações aéreas.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 1500,
      espacoUnitario: 3,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Escafandro de Mergulho',
      descricao: 'Permite operações subaquáticas.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.raro,
      precoBase: 3800,
      espacoUnitario: 4,
      patenteMinima: 2,
    ),
    ItemTemplate(
      nome: 'Traje Ghillie',
      descricao: 'Camuflagem para snipers.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.incomum,
      precoBase: 800,
      espacoUnitario: 2,
      patenteMinima: 1,
    ),
    ItemTemplate(
      nome: 'Uniforme Tático Urbano',
      descricao: 'Roupa resistente para operações na cidade.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 400,
      espacoUnitario: 1,
      patenteMinima: 0,
      defesaBonus: 1,
    ),
    ItemTemplate(
      nome: 'Uniforme de Combate Florestal',
      descricao: 'Camuflagem para ambiente de selva.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 350,
      espacoUnitario: 1,
      patenteMinima: 0,
    ),
    ItemTemplate(
      nome: 'Colete Salva-Vidas Tático',
      descricao: 'Flutuação com porta-equipamentos.',
      tipo: ItemType.equipamento,
      raridade: ItemRarity.comum,
      precoBase: 220,
      espacoUnitario: 2,
      patenteMinima: 0,
    ),
  ];

  /// Retorna todos os templates de um tipo específico
  static List<ItemTemplate> getByType(ItemType type) {
    switch (type) {
      case ItemType.arma:
        return [...armasComuns, ...armasAmaldicoadas];
      case ItemType.cura:
        return [...curas, ...curasAmaldicoadas];
      case ItemType.consumivel:
        return comidas;
      case ItemType.municao:
        return municoes;
      case ItemType.equipamento:
        return [...utilidades, ...equipamentos];
    }
  }

  /// Retorna template aleatório de um tipo específico
  static ItemTemplate getRandomByType(ItemType type) {
    final templates = getByType(type);
    if (templates.isEmpty) {
      throw Exception('Nenhum template encontrado para tipo $type');
    }
    templates.shuffle();
    return templates.first;
  }

  /// Retorna múltiplos templates aleatórios
  static List<ItemTemplate> getRandomMultiple(ItemType type, int quantidade) {
    final templates = List<ItemTemplate>.from(getByType(type));
    templates.shuffle();
    return templates.take(quantidade).toList();
  }

  /// Retorna apenas armas comuns (não amaldiçoadas)
  static List<ItemTemplate> getArmasComuns() => armasComuns;

  /// Retorna apenas armas amaldiçoadas
  static List<ItemTemplate> getArmasAmaldicoadas() => armasAmaldicoadas;

  /// Retorna apenas curas comuns
  static List<ItemTemplate> getCurasComuns() => curas;

  /// Retorna apenas curas amaldiçoadas
  static List<ItemTemplate> getCurasAmaldicoadas() => curasAmaldicoadas;

  /// Retorna todos os templates
  static List<ItemTemplate> getAll() {
    return [
      ...armasComuns,
      ...armasAmaldicoadas,
      ...curas,
      ...curasAmaldicoadas,
      ...comidas,
      ...municoes,
      ...utilidades,
      ...equipamentos,
    ];
  }

  /// Filtra templates por NEX mínimo (retorna todos disponíveis para aquele NEX)
  static List<ItemTemplate> getByNexLevel(int nex) {
    return getAll().where((t) => t.nexMinimo <= nex).toList();
  }

  /// Filtra armas disponíveis para um NEX
  static List<ItemTemplate> getArmasByNex(int nex) {
    return [...armasComuns, ...armasAmaldicoadas]
        .where((t) => t.nexMinimo <= nex)
        .toList();
  }

  /// Filtra consumíveis (curas, comidas) disponíveis para um NEX
  static List<ItemTemplate> getConsumivelsByNex(int nex) {
    return [...curas, ...curasAmaldicoadas, ...comidas]
        .where((t) => t.nexMinimo <= nex)
        .toList();
  }

  /// Filtra equipamentos disponíveis para um NEX
  static List<ItemTemplate> getEquipamentosByNex(int nex) {
    return equipamentos.where((t) => t.nexMinimo <= nex).toList();
  }

  /// Filtra utilidades disponíveis para um NEX
  static List<ItemTemplate> getUtilidadesByNex(int nex) {
    return utilidades.where((t) => t.nexMinimo <= nex).toList();
  }

  /// Retorna apenas items comuns (não amaldiçoados) disponíveis para um NEX
  static List<ItemTemplate> getCommonItemsByNex(int nex) {
    return getAll()
        .where((t) => !t.isAmaldicoado && t.nexMinimo <= nex)
        .toList();
  }

  /// Retorna items iniciais recomendados (NEX 5%)
  static List<ItemTemplate> getStarterItems() {
    return getAll().where((t) => t.nexMinimo == 5 && !t.isAmaldicoado).toList();
  }
}

/// Gerador de nomes de donos de loja
class ShopOwnerNameGenerator {
  static const List<String> nomes = [
    'João', 'Maria', 'Pedro', 'Ana', 'Carlos', 'Paula', 'Ricardo', 'Juliana',
    'Fernando', 'Carla', 'Roberto', 'Beatriz', 'Marcos', 'Luciana', 'André',
    'Patricia', 'Diego', 'Renata', 'Felipe', 'Amanda', 'Gustavo', 'Camila',
    'Rafael', 'Fernanda', 'Bruno', 'Mariana', 'Thiago', 'Aline', 'Leonardo',
    'Daniela', 'Gabriel', 'Vanessa', 'Rodrigo', 'Priscila', 'Lucas', 'Tatiana',
  ];

  static const List<String> sobrenomes = [
    'Silva', 'Santos', 'Oliveira', 'Souza', 'Ferreira', 'Pereira', 'Costa',
    'Rodrigues', 'Almeida', 'Nascimento', 'Lima', 'Araújo', 'Fernandes',
    'Carvalho', 'Gomes', 'Martins', 'Rocha', 'Ribeiro', 'Alves', 'Monteiro',
    'Mendes', 'Barros', 'Freitas', 'Barbosa', 'Pinto', 'Moreira', 'Cunha',
  ];

  static String generate() {
    final random = Random();
    final nome = nomes[random.nextInt(nomes.length)];
    final sobrenome = sobrenomes[random.nextInt(sobrenomes.length)];
    return '$nome $sobrenome';
  }
}
